config/routes.rb
Rails.application.routes.draw do

  get 'user/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users

  resources :items

  resources :bags do
    member do
      get :generate
    end
  end

  root to: "bags#index"
end

app/models/bag.rb
class Bag < ActiveRecord::Base
  belongs_to :user
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :bag
end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :bag
end

app/models/user.rb
class User < ActiveRecord::Base
 def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	      	user.provider = auth.provider
	      	user.uid = auth.uid
	      	user.name = auth.info.name
	      	user.oauth_token = auth.credentials.token
	      	user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	      	user.save!
	    end
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController


	def new

	end

	def create
		@bag = Bag.create(bag_params)
		@bag.user = current_user

		if @bag.save
			redirect_to bags_path
		end
	end

	def index
		@bags = Bag.where(user: current_user)
	end

	def show
		@bag = Bag.find(params[:id])
	end

	def generate
		@bag = Bag.find(params[:id])
		nbr = params[:nbr].to_i
		@items = @bag.items.sample(nbr)
	end

	private

	def bag_params
		params.require(:bag).permit(:name)
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
		
	end

	def new
		@bag = Bag.find(params[:bag_id])
	end

	def create
		@item = Item.new(item_params)
		@bag = Bag.find(item_params[:bag_id])

		if @item.save
			redirect_to @bag
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def destroy
		item = Item.find(params[:id])
		@bag = item.bag

		item.destroy 

		redirect_to @bag
	end

	private

	def item_params
		params.require(:item).permit(:name, :bag_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@current_user = current_user
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/bags/_bag_row.html.erb
<li>
	<%=link_to bag.name, bag %> 
</li>

app/views/bags/generate.html.erb
List generated from
<%= link_to @bag.name, @bag %>

<ul>
	<% @items.each do |item| %>
		<li><%= item.name %></li> 
	<% end %>
</ul>

app/views/bags/index.html.erb
<h1>Bags</h1>
<ul>
	<%= render partial: "bags/bag_row", collection: @bags, as: :bag %>
</ul>

<%= link_to "Add bag", new_bag_path %>

app/views/bags/new.html.erb
<h1>New bag</h1>
<%= form_for Bag.new do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %> 

app/views/bags/show.html.erb
<%= content_tag :h1, @bag.name %>

<%= content_tag :ul do %>
	<% @bag.items.each do |item| %>
		<li><%= link_to item.name, item %> <%= link_to "delete", item_path(item), method: :delete %></li>
	<% end %>
<% end %>

<%#= link_to "Add item", controller: :items, action: :new, bag_id: @bag %>

<%= form_for Item.new do |f| %>
	<%= f.hidden_field :bag_id, value: @bag.id %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

<%= form_tag({ controller: :bags, action: :generate}, id: @bag, method: :get ) do %>
	<%= range_field_tag :nbr, 1, min: 1, max: @bag.items.count, step: 1 %>
	<%= submit_tag "Generate list" %>
<% end %>

app/views/items/_item_row.html.erb
<li>
	<%= item.name %>
</li>

app/views/items/index.html.erb
<h1>Items</h1>
<ul>
	<%= render partial: "items/item_row", collection: @items, as: :item %>
</ul>

app/views/items/new.html.erb
New!

<%= @bag.name %>

<%= form_for Item.new do |f| %>
	<%= f.hidden_field :bag_id, value: @bag.id %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/items/show.html.erb
<%= content_tag :h1, @item.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mixbag</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
	<%= render partial: "users/user_row", collection: @users, as: :user  %>
</ul>